const fs=require('fs');
const re=fs.readFileSync('services/riskEngine.js','utf8');
const ps=fs.readFileSync('services/payoutService.js','utf8');
const ar=fs.readFileSync('routes/admin.routes.js','utf8');
const cs=fs.readFileSync('services/challengeService.js','utf8');
const mig=fs.readFileSync('db/terminal-migrations/022_twostep_risk_profile.sql','utf8');
const svc=fs.readFileSync('services/twoStepRiskProfileService.js','utf8');
let p=0,f=0;
const ok=m=>{console.log('  V '+m);p++;};
const er=m=>{console.error('  X '+m);f++;};
svc.includes('isTwoStepAccount')?ok('svc:isTwoStepAccount'):er('svc:isTwoStepAccount');
svc.includes('getPhase')?ok('svc:getPhase'):er('svc:getPhase');
svc.includes('getEffectiveSplitPct')?ok('svc:getEffectiveSplitPct'):er('svc:getEffectiveSplitPct');
svc.includes('f_profit_split_initial_pct:80')?ok('svc:split=80'):er('svc:split!=80');
svc.includes('f_profit_split_scaled_pct:90')?ok('svc:split=90'):er('svc:split!=90');
svc.includes('time_limit_days:0')?ok('svc:unlimited'):er('svc:time_limit!=0');
re.includes('TwoStepRiskProfileService')?ok('RE:imported'):er('RE:not imported');
re.includes('isTwoStepAccount(account)')?ok('RE:isTwoStepAccount'):er('RE:missing');
re.includes('_twostep_weekend_allowed')?ok('RE:weekend'):er('RE:weekend missing');
re.includes('TwoStepRiskProfileService.isTwoStepAccount(account))')?ok('RE:leverage'):er('RE:leverage not 2step');
ps.includes('TwoStepRiskProfileService')?ok('PS:imported'):er('PS:not imported');
ps.includes('isTwoStep')?ok('PS:isTwoStep'):er('PS:missing');
ps.includes('f_payout_threshold_pct')?ok('PS:threshold'):er('PS:threshold missing');
ar.includes('twostep/profile')?ok('Admin:routes'):er('Admin:routes missing');
ar.includes('twostep/audit')?ok('Admin:audit'):er('Admin:audit missing');
ar.includes('first_payout_approved_at')?ok('Admin:payout_status'):er('Admin:payout_status');
cs.includes('durationDays: 0')?ok('CS:unlimited'):er('CS:not unlimited');
mig.includes('twostep_risk_profile')?ok('MIG:table'):er('MIG:table');
mig.includes('first_payout_approved_at')?ok('MIG:column'):er('MIG:column');
!mig.includes('DROP')?ok('MIG:safe'):er('MIG:destructive');
mig.includes("DEFAULT '15:30'")?ok('MIG:hours'):er('MIG:hours wrong');
mig.includes('DEFAULT 0,')?ok('MIG:time_limit=0'):er('MIG:time_limit');
console.log('\n  2-STEP SUITE: '+p+' passed, '+f+' failed');
process.exit(f>0?1:0);